[package]
name = "ch_1_ANN"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
candle-core = "0.6.0"
candle-nn = "0.6.0"
serde = "1.0.205"
serde_json = "1.0.122"
